/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvtalRouteImport } from './routes/avtal'
import { Route as EkonomiRouteImport } from './routes/ekonomi'
import { Route as FastighetenRouteImport } from './routes/fastigheten'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as HyresobjektRouteImport } from './routes/hyresobjekt'
import { Route as StyrelsemoteRouteImport } from './routes/styrelsemote'
import { Route as UnderhallRouteImport } from './routes/underhall'
import { Route as EkonomiInvesteringssimulatorRouteImport } from './routes/ekonomi.investeringssimulator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvtalRoute = AvtalRouteImport.update({
  id: '/avtal',
  path: '/avtal',
  getParentRoute: () => rootRouteImport,
} as any)
const EkonomiRoute = EkonomiRouteImport.update({
  id: '/ekonomi',
  path: '/ekonomi',
  getParentRoute: () => rootRouteImport,
} as any)
const FastighetenRoute = FastighetenRouteImport.update({
  id: '/fastigheten',
  path: '/fastigheten',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const HyresobjektRoute = HyresobjektRouteImport.update({
  id: '/hyresobjekt',
  path: '/hyresobjekt',
  getParentRoute: () => rootRouteImport,
} as any)
const StyrelsemoteRoute = StyrelsemoteRouteImport.update({
  id: '/styrelsemote',
  path: '/styrelsemote',
  getParentRoute: () => rootRouteImport,
} as any)
const UnderhallRoute = UnderhallRouteImport.update({
  id: '/underhall',
  path: '/underhall',
  getParentRoute: () => rootRouteImport,
} as any)
const EkonomiInvesteringssimulatorRoute =
  EkonomiInvesteringssimulatorRouteImport.update({
    id: '/investeringssimulator',
    path: '/investeringssimulator',
    getParentRoute: () => EkonomiRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avtal': typeof AvtalRoute
  '/ekonomi': typeof EkonomiRouteWithChildren
  '/fastigheten': typeof FastighetenRoute
  '/garage': typeof GarageRoute
  '/hyresobjekt': typeof HyresobjektRoute
  '/styrelsemote': typeof StyrelsemoteRoute
  '/underhall': typeof UnderhallRoute
  '/ekonomi/investeringssimulator': typeof EkonomiInvesteringssimulatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avtal': typeof AvtalRoute
  '/ekonomi': typeof EkonomiRouteWithChildren
  '/fastigheten': typeof FastighetenRoute
  '/garage': typeof GarageRoute
  '/hyresobjekt': typeof HyresobjektRoute
  '/styrelsemote': typeof StyrelsemoteRoute
  '/underhall': typeof UnderhallRoute
  '/ekonomi/investeringssimulator': typeof EkonomiInvesteringssimulatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avtal': typeof AvtalRoute
  '/ekonomi': typeof EkonomiRouteWithChildren
  '/fastigheten': typeof FastighetenRoute
  '/garage': typeof GarageRoute
  '/hyresobjekt': typeof HyresobjektRoute
  '/styrelsemote': typeof StyrelsemoteRoute
  '/underhall': typeof UnderhallRoute
  '/ekonomi/investeringssimulator': typeof EkonomiInvesteringssimulatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avtal'
    | '/ekonomi'
    | '/fastigheten'
    | '/garage'
    | '/hyresobjekt'
    | '/styrelsemote'
    | '/underhall'
    | '/ekonomi/investeringssimulator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avtal'
    | '/ekonomi'
    | '/fastigheten'
    | '/garage'
    | '/hyresobjekt'
    | '/styrelsemote'
    | '/underhall'
    | '/ekonomi/investeringssimulator'
  id:
    | '__root__'
    | '/'
    | '/avtal'
    | '/ekonomi'
    | '/fastigheten'
    | '/garage'
    | '/hyresobjekt'
    | '/styrelsemote'
    | '/underhall'
    | '/ekonomi/investeringssimulator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvtalRoute: typeof AvtalRoute
  EkonomiRoute: typeof EkonomiRouteWithChildren
  FastighetenRoute: typeof FastighetenRoute
  GarageRoute: typeof GarageRoute
  HyresobjektRoute: typeof HyresobjektRoute
  StyrelsemoteRoute: typeof StyrelsemoteRoute
  UnderhallRoute: typeof UnderhallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avtal': {
      id: '/avtal'
      path: '/avtal'
      fullPath: '/avtal'
      preLoaderRoute: typeof AvtalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ekonomi': {
      id: '/ekonomi'
      path: '/ekonomi'
      fullPath: '/ekonomi'
      preLoaderRoute: typeof EkonomiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fastigheten': {
      id: '/fastigheten'
      path: '/fastigheten'
      fullPath: '/fastigheten'
      preLoaderRoute: typeof FastighetenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hyresobjekt': {
      id: '/hyresobjekt'
      path: '/hyresobjekt'
      fullPath: '/hyresobjekt'
      preLoaderRoute: typeof HyresobjektRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styrelsemote': {
      id: '/styrelsemote'
      path: '/styrelsemote'
      fullPath: '/styrelsemote'
      preLoaderRoute: typeof StyrelsemoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/underhall': {
      id: '/underhall'
      path: '/underhall'
      fullPath: '/underhall'
      preLoaderRoute: typeof UnderhallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ekonomi/investeringssimulator': {
      id: '/ekonomi/investeringssimulator'
      path: '/investeringssimulator'
      fullPath: '/ekonomi/investeringssimulator'
      preLoaderRoute: typeof EkonomiInvesteringssimulatorRouteImport
      parentRoute: typeof EkonomiRoute
    }
  }
}

interface EkonomiRouteChildren {
  EkonomiInvesteringssimulatorRoute: typeof EkonomiInvesteringssimulatorRoute
}

const EkonomiRouteChildren: EkonomiRouteChildren = {
  EkonomiInvesteringssimulatorRoute: EkonomiInvesteringssimulatorRoute,
}

const EkonomiRouteWithChildren =
  EkonomiRoute._addFileChildren(EkonomiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvtalRoute: AvtalRoute,
  EkonomiRoute: EkonomiRouteWithChildren,
  FastighetenRoute: FastighetenRoute,
  GarageRoute: GarageRoute,
  HyresobjektRoute: HyresobjektRoute,
  StyrelsemoteRoute: StyrelsemoteRoute,
  UnderhallRoute: UnderhallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
